// Single source of truth for the Tallyhawk mark. The inline React logo, the OG images and the
// static icon files generated by `npm run brand:assets` all draw from these constants, so the
// mark can't drift between surfaces. Keep this file free of imports and non-erasable TS syntax:
// scripts/generate-brand-assets.mjs imports it directly with Node's type stripping.

export const BRAND_NAME = "Tallyhawk";

export const BRAND_COLORS = {
  indigoLight: "#818CF8",
  indigo: "#6366F1",
  emerald: "#10B981",
  ink: "#07080F",
  white: "#FFFFFF",
} as const;

export const LOGO_VIEWBOX_SIZE = 64;
export const LOGO_TILE_RADIUS = 15;

/** Diagonal indigo → emerald sweep used behind the hawk, in 64×64 user space. */
export const LOGO_GRADIENT = {
  x1: 8,
  y1: 6,
  x2: 58,
  y2: 60,
  stops: [
    { offset: 0, color: BRAND_COLORS.indigoLight },
    { offset: 0.55, color: BRAND_COLORS.indigo },
    { offset: 1, color: BRAND_COLORS.emerald },
  ],
} as const;

/**
 * Geometric hawk head in profile, facing right. Subpaths, in order: the head (crown, hooked beak,
 * gape), the eye cut out of it, then two ledger rows that the neck dissolves into — the hawk
 * turning paperwork into rows of data. Render with fill-rule="evenodd" so the eye is a hole.
 */
export const LOGO_HAWK_PATH = [
  "M16.6 40.2L17.5 33C18.6 22.5 25.5 15.5 35 15L43.5 15.3C51.8 15.6 57 21 56.7 27.8C56.5 31.6 55.2 34.8 52.8 37.6L49.2 31L44.6 31.9L42.59 40.2Z",
  "M33.2 22.6L43.6 22.6L39.2 27.4C36.6 27.6 34.4 25.6 33.2 22.6Z",
  "M16.28 42.8L41.97 42.8L41.14 46.2L15.85 46.2Z",
  "M15.53 48.8L40.52 48.8L39.5 53L15 53Z",
].join("");

interface LogoSvgOptions {
  /** Rounded tile (default) or a full-bleed square for platforms that apply their own mask. */
  shape?: "rounded" | "square";
  /** Scale of the hawk inside the tile; < 1 keeps it inside a maskable icon's safe zone. */
  hawkScale?: number;
  gradientId?: string;
}

/** Standalone SVG document for the mark — used for app/icon.svg, public/logo.svg and rasterizing. */
export function logoSvg({
  shape = "rounded",
  hawkScale = 1,
  gradientId = "tallyhawk-gradient",
}: LogoSvgOptions = {}): string {
  const size = LOGO_VIEWBOX_SIZE;
  const radius = shape === "rounded" ? LOGO_TILE_RADIUS : 0;
  const stops = LOGO_GRADIENT.stops
    .map((stop) => `<stop offset="${stop.offset}" stop-color="${stop.color}"/>`)
    .join("");
  const offset = (size - size * hawkScale) / 2;
  const transform =
    hawkScale === 1 ? "" : ` transform="translate(${offset} ${offset}) scale(${hawkScale})"`;

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">`,
    `<title>${BRAND_NAME}</title>`,
    `<defs><linearGradient id="${gradientId}" x1="${LOGO_GRADIENT.x1}" y1="${LOGO_GRADIENT.y1}" x2="${LOGO_GRADIENT.x2}" y2="${LOGO_GRADIENT.y2}" gradientUnits="userSpaceOnUse">${stops}</linearGradient></defs>`,
    `<rect width="${size}" height="${size}" rx="${radius}" fill="url(#${gradientId})"/>`,
    `<path d="${LOGO_HAWK_PATH}" fill="${BRAND_COLORS.white}" fill-rule="evenodd"${transform}/>`,
    `</svg>`,
  ].join("");
}
